---
apiVersion: v1
kind: Secret
metadata:
  name: scraper-secrets
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: "***"
  SPRING_DATASOURCE_PASSWORD: "***"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scraper-config
data:
  SPRING_DATASOURCE_URL: "***"
  SPRING_DATASOURCE_USERNAME: "***"
  
  TELEGRAM_CHAT_ID: "***"
  
  SCRAPER_USER_AGENT: "***"
  SCRAPER_PROVIDERS_CVBANKAS_URL: "***"
  SCRAPER_PROVIDERS_CVBANKAS_CRON: "***"
  SCRAPER_PROVIDERS_CVBANKAS_NAME: "***"
  SCRAPER_PROVIDERS_CVBANKAS_DELAY_MIN: "***"
  SCRAPER_PROVIDERS_CVBANKAS_DELAY_MAX: "***"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-scraper
  template:
    metadata:
      labels:
        app: job-scraper
    spec:
      containers:
        - name: scraper
          image: "***/***:***"
          envFrom:
            - secretRef:
                name: scraper-secrets
            - configMapRef:
                name: scraper-config
          resources:
            requests:
              memory: "100Mi"
            limits:
              memory: "450Mi"